import mongoose from 'mongoose';

const productSchema = new mongoose.Schema(
  {
    name: {
      type: String,
      required: [true, 'Product name is required'],
      trim: true,
      maxlength: [100, 'Product name cannot exceed 100 characters'],
    },
    normalizedName: {
      type: String,
      trim: true,
      lowercase: true,
      default: '',
    },
    sku: {
      type: String,
      required: [true, 'SKU is required'],
      unique: true,
      trim: true,
      uppercase: true,
    },
    barcode: {
      type: String,
      trim: true,
      default: '',
    },
    description: {
      type: String,
      trim: true,
      maxlength: [500, 'Description cannot exceed 500 characters'],
    },
    category: {
      type: mongoose.Schema.Types.ObjectId,
      ref: 'Category',
      required: [true, 'Category is required'],
    },
    subcategoryId: {
      type: mongoose.Schema.Types.ObjectId,
      ref: 'Subcategory',
    },
    hsnCode: {
      type: String,
      trim: true,
      default: '',
    },
    hsnAutoGenerated: {
      type: Boolean,
      default: false,
    },
    source: {
      type: String,
      enum: ['manual', 'purchase', 'opening_stock', 'import'],
      default: 'manual',
    },

    stock: {
      type: Number,
      required: [true, 'Stock quantity is required'],
      min: [0, 'Stock cannot be negative'],
      default: 0,
    },
    lowStockThreshold: {
      type: Number,
      default: 10,
      min: [0, 'Threshold cannot be negative'],
    },
    image: {
      type: String,
      default: '',
    },
    images: {
      type: [String],
      default: [],
    },
    unit: {
      type: String,
      enum: ["piece", "kg", "liter", "meter", "box", "dozen"],
      default: "piece",
    },
    salesPrice: {
      type: Number,
      default: 0,
      min: [0, 'Sales price cannot be negative'],
    },
    salesTaxType: {
      type: String,
      enum: ["with", "without"],
      default: "without",
    },
    purchasePrice: {
      type: Number,
      default: 0,
      min: [0, 'Purchase price cannot be negative'],
    },
    purchaseTaxType: {
      type: String,
      enum: ["with", "without"],
      default: "without",
    },
    taxRate: {
      type: Number,
      default: 0,
      min: [0, 'Tax rate cannot be negative'],
    },
    openingStockPrice: {
      type: Number,
      default: 0,
      min: [0, 'Opening stock price cannot be negative'],
    },
    openingStockDate: {
      type: Date,
      default: Date.now,
    },
    isActive: {
      type: Boolean,
      default: true,
    },
  },
  {
    timestamps: true,
    toJSON: { virtuals: true },
    toObject: { virtuals: true },
  }
);

productSchema.pre('validate', function (next) {
  if (this.name) {
    this.normalizedName = this.name.trim().replace(/\s+/g, ' ').toLowerCase();
  }
  next();
});

productSchema.pre('findOneAndUpdate', function (next) {
  const update = this.getUpdate() || {};
  const name = update.name || update.$set?.name;
  if (name) {
    const normalizedName = name.trim().replace(/\s+/g, ' ').toLowerCase();
    if (update.$set) update.$set.normalizedName = normalizedName;
    else update.normalizedName = normalizedName;
  }
  next();
});



// Virtual for low stock status
productSchema.virtual('isLowStock').get(function () {
  return this.stock <= this.lowStockThreshold;
});

// Index for search
productSchema.index({ name: 'text', sku: 'text', barcode: 'text' });
productSchema.index({ normalizedName: 1, unit: 1 });
productSchema.index({ category: 1, isActive: 1 });
productSchema.index({ stock: 1, lowStockThreshold: 1 });

export default mongoose.model('Product', productSchema);
